name: Upload Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tagId:
        description: 'Tag'     
        required: true
        default: 'v1.0.0'
jobs:

  build:
    runs-on: ubuntu-latest    
    steps:

    - name: Get tag version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "RELEASE_VERSION=${{ github.event.inputs.tagId }}" >> $GITHUB_ENV
        else
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        fi

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ env.RELEASE_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install npm
      run: npm ci

    - name: Rollup
      run: npm run rollup

    - name: Copy css, skin, etc...
      run: |
        cp README.md dist
        cp LICENSE dist

    - name: Rename build to openlime
      run: mv dist openlime

    - name: Install Zip 
      uses: montudor/action-zip@v1

    - name: ZIP Output  
      run: zip -qq -r openlime-${{ env.RELEASE_VERSION }}.zip openlime

    - name: Create commits list
      run: jsdoc/releases/gen_changelog.sh >> jsdoc/releases/rel-${{ env.RELEASE_VERSION }}.md

    - name: Create automatic release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "openlime-${{ env.RELEASE_VERSION }}.zip"
        bodyFile: "jsdoc/releases/rel-${{ env.RELEASE_VERSION }}.md"
        tag: ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
